import { useState } from "react";
import { Check, CheckCircle2, Circle, FileCheck2, GitCommitHorizontal, History, ScanSearch, ShieldCheck, UserRound } from "lucide-react";
import { auditTasks } from "../types";
import { Badge, Button, Card, CardContent, CardHeader, StatusBadge, SurfaceHeader } from "../components/ui-primitives";
import { PageFrame } from "../components/PageFrame";

const auditNodes = [{ label: "身份", detail: "主体 DID 已关联" }, { label: "数据", detail: "摘要 Hash 匹配" }, { label: "Policy", detail: "使用规则已冻结" }, { label: "Contract", detail: "协商条件一致" }, { label: "计算", detail: "结果回执已生成" }, { label: "结果", detail: "人工确认待完成" }, { label: "存证", detail: "DEMO 索引待接入" }];

export function AuditCenterPage() {
  const [selected, setSelected] = useState(auditTasks[0]);
  return <PageFrame title="审计中心" description="以任务为主线复核身份、数据、规则、计算、结果与证据锚定。" action={<Button variant="secondary"><History size={14} />导出审计摘要</Button>}>
    <div className="trusted-audit-layout"><Card className="trusted-audit-list"><CardHeader><SurfaceHeader title="TTC 列表" description={`${auditTasks.length} 项本地审计样例`} action={<ScanSearch size={16} />} /></CardHeader><CardContent><div className="trusted-audit-items">{auditTasks.map((task) => <button className={`trusted-audit-item${selected.id === task.id ? " is-selected" : ""}`} type="button" key={task.id} onClick={() => setSelected(task)}><div><strong><code>{task.id}</code></strong><StatusBadge value={task.status} /></div><span>{task.title}</span><small>{task.time}</small></button>)}</div><Button variant="link" size="sm" className="trusted-audit-more">查看更多任务</Button></CardContent></Card><div className="trusted-audit-detail"><Card><CardHeader><SurfaceHeader title={`审计链 · ${selected.id}`} description={`${selected.title} · 来源：${selected.source}`} action={<Badge tone="warning">演示审计样例</Badge>} /></CardHeader><CardContent><div className="trusted-audit-graph">{auditNodes.map((node, index) => <div className="trusted-audit-node-wrap" key={node.label}><div className="trusted-audit-node"><span>{index < 5 ? <Check size={14} /> : <Circle size={12} />}</span><strong>{node.label}</strong><small>{node.detail}</small></div>{index < auditNodes.length - 1 && <i className={`trusted-audit-link${index < 4 ? " is-done" : ""}`} />}</div>)}</div><div className="trusted-audit-source"><span><GitCommitHorizontal size={15} />证据链来源</span><code>LOCAL_EVIDENCE_LEDGER_V1</code><Badge tone="warning">DEMO</Badge></div></CardContent></Card><Card><CardHeader><SurfaceHeader title="审计结论" description="结论评级仅针对当前本地演示样例" action={<FileCheck2 size={16} />} /></CardHeader><CardContent><div className="trusted-audit-conclusion"><span className="trusted-pass-mark"><CheckCircle2 size={23} /></span><div><span>审计结论</span><strong>PASS</strong><small>来源：本地受控审计样例 · 2026-05-18 10:00</small></div><Badge tone="success">低风险</Badge></div><div className="trusted-audit-facts"><div><span><UserRound size={14} />审计主体</span><strong>审计工作组</strong></div><div><span><ShieldCheck size={14} />审计 Agent</span><strong>AuditAgent-001</strong></div><div><span><Circle size={14} />未完成节点</span><strong>结果确认、DEMO 存证</strong></div></div><Button variant="secondary">查看完整审计报告</Button></CardContent></Card></div></div>
  </PageFrame>;
}
