import { CheckCircle2, Copy, FileKey2, Fingerprint, Link2, LockKeyhole, RefreshCw, ShieldCheck, UserRound } from "lucide-react";
import { identityProfile, capabilityMatrix } from "../types";
import { Badge, Button, Card, CardContent, CardHeader, Divider, IconButton, StatusBadge, SurfaceHeader } from "../components/ui-primitives";
import { PageFrame } from "../components/PageFrame";

export function IdentityPage() {
  return <PageFrame title="身份中心" description="管理当前主体的 DID、数字证书与 Connector 适配边界。" action={<Button variant="secondary"><RefreshCw size={14} />刷新身份状态</Button>}>
    <div className="trusted-detail-grid trusted-identity-grid">
      <div className="trusted-detail-main"><Card><CardHeader><SurfaceHeader title="主体信息" description="由当前登录会话与身份适配器共同提供" action={<Badge tone="success" dot>已验证</Badge>} /></CardHeader><CardContent><div className="trusted-profile-block"><span className="trusted-profile-avatar"><UserRound size={24} /></span><div><h3>{identityProfile.subject}</h3><p>{identityProfile.role}</p><Badge tone="brand">{identityProfile.organizationId}</Badge></div></div><Divider /><dl className="trusted-definition-grid"><div><dt>主体名称</dt><dd>{identityProfile.subject}</dd></div><div><dt>主体类型</dt><dd>{identityProfile.role}</dd></div><div><dt>组织标识</dt><dd><code>{identityProfile.organizationId}</code><IconButton label="复制组织标识"><Copy size={13} /></IconButton></dd></div><div><dt>主体状态</dt><dd><StatusBadge value="已连接" /></dd></div></dl></CardContent></Card><Card><CardHeader><SurfaceHeader title="数字证书" description="证书链由本地受控环境提供" action={<FileKey2 size={17} />} /></CardHeader><CardContent><dl className="trusted-definition-grid"><div><dt>证书颁发方</dt><dd>{identityProfile.certificate.split(" / ")[0]}</dd></div><div><dt>证书状态</dt><dd><Badge tone="success" dot>有效</Badge></dd></div><div><dt>生效时间</dt><dd className="trusted-mono">{identityProfile.issuedAt}</dd></div><div><dt>有效期至</dt><dd className="trusted-mono">{identityProfile.expiresAt}</dd></div></dl><Button variant="secondary"><FileKey2 size={14} />查看证书摘要</Button></CardContent></Card></div>
      <div className="trusted-detail-side"><Card><CardHeader><SurfaceHeader title="DID 信息" description="分布式数字身份标识" action={<Fingerprint size={17} />} /></CardHeader><CardContent><div className="trusted-did-value"><code>{identityProfile.did}</code><IconButton label="复制 DID"><Copy size={13} /></IconButton></div><dl className="trusted-definition-list"><div><dt>创建时间</dt><dd>2026-03-01 10:00:00</dd></div><div><dt>更新时间</dt><dd>2026-05-18 09:12:00</dd></div><div><dt>密钥托管</dt><dd><Badge tone="warning">本地适配器</Badge></dd></div></dl><div className="trusted-note"><LockKeyhole size={14} /><span>私钥不离开当前受控环境，DID 登录能力仍需部署端配置。</span></div></CardContent></Card><Card><CardHeader><SurfaceHeader title="EDC / Connector" description="连接器绑定状态与适配器边界" action={<Link2 size={17} />} /></CardHeader><CardContent><dl className="trusted-definition-list"><div><dt>Connector ID</dt><dd><code>{identityProfile.connector}</code></dd></div><div><dt>类型</dt><dd>{identityProfile.connectorType}</dd></div><div><dt>当前能力</dt><dd><Badge tone="warning" dot>ADAPTER</Badge></dd></div><div><dt>连接状态</dt><dd><StatusBadge value="已连接" /></dd></div></dl><Button variant="secondary"><Link2 size={14} />管理 Connector</Button></CardContent></Card></div>
    </div>
    <Card className="trusted-capability-card"><CardHeader><SurfaceHeader title="可信能力矩阵" description="每项能力都显示真实接入边界，演示状态不会被当作生产结论。" /></CardHeader><CardContent><div className="trusted-capability-table">{capabilityMatrix.map((item) => <div className="trusted-capability-row" key={item.name}><span className="trusted-capability-name"><ShieldCheck size={15} />{item.name}</span><Badge tone={item.truth === "BLOCKED" ? "danger" : item.truth === "DEMO" || item.truth === "ADAPTER" ? "warning" : "success"}>{item.truth}</Badge><span className="trusted-muted">{item.note}</span><CheckCircle2 size={15} className={item.truth === "BLOCKED" ? "trusted-icon-muted" : "trusted-icon-success"} /></div>)}</div></CardContent></Card>
  </PageFrame>;
}
