import { ArrowRight, CheckCircle2, Cpu, Link2, Network, Radio, ShieldCheck, TerminalSquare } from "lucide-react";
import { participants } from "../types";
import { Badge, Button, Card, CardContent, CardHeader, Progress, StatusBadge, SurfaceHeader } from "../components/ui-primitives";
import { PageFrame } from "../components/PageFrame";

export function MpcPage() {
  return <PageFrame title="MPC 计算任务" description="查看参与方拓扑、互联状态和受控计算日志。" back="/trusted-space/ttc/ttc-20260518-001" action={<Badge tone="warning" dot>LOCAL_REAL_EXPERIMENTAL_SINGLE_HOST</Badge>}>
    <div className="trusted-mpc-alert"><ShieldCheck size={16} /><div><strong>能力边界提示</strong><span>此页面仅展示当前主机上的确定性实验流程，不构成生产跨域 MPC、TEE 或远程证明。</span></div><Badge tone="warning">本地实验</Badge></div>
    <div className="trusted-mpc-grid"><Card className="trusted-topology-card"><CardHeader><SurfaceHeader title="参与方拓扑" description="三方摘要输入通过本地受控适配器汇聚" action={<Network size={16} />} /></CardHeader><CardContent><div className="trusted-topology"><div className="trusted-topology-lines"><i className="topology-line topology-line-a" /><i className="topology-line topology-line-b" /><i className="topology-line topology-line-c" /></div>{participants.map((party) => <div className={`trusted-party-card trusted-party-${party.id}`} key={party.id}><span className="trusted-party-icon"><Cpu size={16} /></span><strong>{party.name}</strong><small>{party.role}</small><code>{party.did}</code><StatusBadge value={party.status} /></div>)}<div className="trusted-mpc-core"><span><Network size={18} /></span><strong>MPC 计算节点</strong><small>本地受控实验核心</small><Badge tone="warning">实验态</Badge></div></div><div className="trusted-topology-legend"><span><i className="trusted-dot trusted-dot-success" />已连接</span><span><i className="trusted-dot trusted-dot-info" />摘要传输</span><span><i className="trusted-dot trusted-dot-warning" />适配器边界</span></div></CardContent></Card><Card className="trusted-mpc-log-card"><CardHeader><SurfaceHeader title="实时计算日志" description="最近 6 条受控执行事件" action={<TerminalSquare size={16} />} /></CardHeader><CardContent><div className="trusted-log-stream trusted-log-compact">{["party-a digest accepted", "party-b input sealed", "party-c connector adapter ready", "batch 03/05 executing", "result digest pending", "audit hook staged"].map((line, index) => <div key={line}><time>09:{35 + Math.floor(index / 2)}:{String(4 + index * 3).padStart(2, "0")}</time><code>{line}</code><CheckCircle2 size={13} /></div>)}</div><div className="trusted-mpc-progress"><Progress value={65} label="计算进度 65%" /><span>预计还需 00:01:24</span></div><Button variant="secondary"><Radio size={14} />订阅本地日志</Button></CardContent></Card></div>
    <Card><CardHeader><SurfaceHeader title="参与方回执" description="回执哈希只用于本次本地实验关联" action={<Link2 size={16} />} /></CardHeader><CardContent><div className="trusted-receipt-table">{participants.map((party, index) => <div key={party.id}><span><strong>{party.role}</strong><small>{party.name}</small></span><code>{["0x3e1a…8fb2", "0x72cc…10d4", "0xd81f…4a63"][index]}</code><Badge tone="success" dot>已回执</Badge><ArrowRight size={14} /></div>)}</div></CardContent></Card>
  </PageFrame>;
}
