import { BadgeCheck, Blocks, Copy, Hash, Link2, ShieldCheck } from "lucide-react";
import { Badge, Button, Card, CardContent, CardHeader, IconButton, MetricBand, SurfaceHeader, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../components/ui-primitives";
import { PageFrame } from "../components/PageFrame";

export function ResultsEvidencePage() {
  return <PageFrame title="计算结果与存证" description="结果摘要、验证哈希和证据记录分层展示，所有数值均为演示夹具。" back="/trusted-space/mpc/com-20260518-001" action={<Badge tone="success" dot>已验证 · 演示样例</Badge>}>
    <div className="trusted-result-notice"><Badge tone="warning">演示数据</Badge><span>以下电量、价格与金额来自本地确定性执行面，仅用于展示结果复核流程，不构成生产结算或已上链事实。</span></div>
    <MetricBand items={[{ label: "结算电量", value: "100.00 MWh", detail: "2026-05 结算窗口", tone: "brand" }, { label: "结算价格", value: "320.00 元/MWh", detail: "规则 Settlement_v1.0.5", tone: "info" }, { label: "结算金额", value: "32,000.00 元", detail: "仅供演示核验", tone: "success" }, { label: "生成时间", value: "09:45:00", detail: "2026-05-18", tone: "warning" }]} />
    <div className="trusted-result-grid"><Card><CardHeader><SurfaceHeader title="结果摘要" description="由本地受控计算生成的可核验摘要" action={<BadgeCheck size={16} />} /></CardHeader><CardContent className="trusted-table-wrap"><Table><TableHeader><TableRow><TableHead>指标</TableHead><TableHead>结果</TableHead><TableHead>口径</TableHead><TableHead>校验</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>结算电量</TableCell><TableCell><strong className="trusted-result-number">100.00 MWh</strong></TableCell><TableCell>聚合场站出力</TableCell><TableCell><Badge tone="success">PASS</Badge></TableCell></TableRow><TableRow><TableCell>结算价格</TableCell><TableCell><strong className="trusted-result-number">320.00 元/MWh</strong></TableCell><TableCell>区域交易规则</TableCell><TableCell><Badge tone="success">PASS</Badge></TableCell></TableRow><TableRow><TableCell>结算金额</TableCell><TableCell><strong className="trusted-result-number">32,000.00 元</strong></TableCell><TableCell>电量 × 价格</TableCell><TableCell><Badge tone="success">PASS</Badge></TableCell></TableRow></TableBody></Table></CardContent></Card><Card><CardHeader><SurfaceHeader title="可信验证" description="摘要哈希与输入关联" action={<Hash size={16} />} /></CardHeader><CardContent><div className="trusted-hash-list"><div><span>ResultHash</span><code>7ab3…c91f</code><IconButton label="复制 ResultHash"><Copy size={13} /></IconButton><Badge tone="success">有效</Badge></div><div><span>规则 Hash</span><code>a1b2…d0e1</code><IconButton label="复制规则 Hash"><Copy size={13} /></IconButton><Badge tone="success">匹配</Badge></div><div><span>数据 Hash</span><code>b2c3…e0f2</code><IconButton label="复制数据 Hash"><Copy size={13} /></IconButton><Badge tone="success">匹配</Badge></div><div><span>输入 Hash</span><code>d4e5…f1g3</code><IconButton label="复制输入 Hash"><Copy size={13} /></IconButton><Badge tone="success">有效</Badge></div></div><DividerLike /></CardContent></Card></div>
    <Card><CardHeader><SurfaceHeader title="上链存证记录" description="链路适配器返回的演示索引，不代表真实区块链写入" action={<Blocks size={16} />} /></CardHeader><CardContent><div className="trusted-chain-record"><div><small>区块链</small><strong>FISCO BCOS <Badge tone="warning">DEMO</Badge></strong></div><div><small>交易哈希</small><code>0xbAf3…d2c9</code></div><div><small>区块高度</small><strong>1256789</strong></div><div><small>存证时间</small><time>2026-05-18 09:48</time></div><div><small>锚定状态</small><Badge tone="warning" dot>待接入真实节点</Badge></div><Button variant="secondary"><Link2 size={14} />查看证据索引</Button></div><div className="trusted-result-footnote"><ShieldCheck size={14} />结果确认人与证据来源需以真实服务端回执为准。</div></CardContent></Card>
  </PageFrame>;
}

function DividerLike() {
  return <div className="trusted-divider-spacer" />;
}
