import { useState } from "react";
import { Activity, Check, ClipboardList, FileClock, ListChecks, Logs, ShieldCheck } from "lucide-react";
import { ttcTimeline } from "../types";
import { Badge, Button, Card, CardContent, CardHeader, Dialog, DialogContent, DialogDescription, DialogTitle, Progress, StatusBadge, SurfaceHeader, Timeline } from "../components/ui-primitives";
import { PageFrame } from "../components/PageFrame";

export function TtcPage() {
  const [logsOpen, setLogsOpen] = useState(false);
  return <PageFrame title="TTC 任务详情" description="沿状态机追踪主体、数据授权、受控计算和证据归档节点。" back="/trusted-space/workbench" action={<><StatusBadge value="计算中" /><Button variant="secondary" onClick={() => setLogsOpen(true)}><Logs size={14} />实时日志</Button></>}>
    <Card className="trusted-task-banner"><CardContent><div><small>任务 ID</small><strong><code>TTC-20260518-001</code></strong></div><div><small>任务类型</small><strong>结算计算</strong></div><div><small>发起方</small><strong>东部交易中心</strong></div><div><small>数据版本</small><strong><code>V3.2</code></strong></div><div><small>规则版本</small><strong><code>Settlement_v1.0.5</code></strong></div><div><small>当前 Agent</small><Badge tone="warning">演示助手</Badge></div></CardContent></Card>
    <Card className="trusted-state-card"><CardHeader><SurfaceHeader title="状态轨迹" description="状态按确定性任务夹具展示，实时生产状态仍以服务端为准" action={<Badge tone="info" dot>ComputeExec</Badge>} /></CardHeader><CardContent><div className="trusted-state-tracker">{ttcTimeline.map((event, index) => <div className={`trusted-state-node trusted-state-${event.state}`} key={event.id}><span className="trusted-state-marker">{event.state === "done" ? <Check size={13} /> : event.state === "current" ? <Activity size={13} /> : index + 1}</span><strong>{event.label}</strong><small>{event.time}</small>{index < ttcTimeline.length - 1 && <i className="trusted-state-connector" />}</div>)}</div></CardContent></Card>
    <div className="trusted-ttc-grid"><Card><CardHeader><SurfaceHeader title="节点事件" description="纵向事件顺序与时间戳" action={<FileClock size={16} />} /></CardHeader><CardContent><Timeline events={ttcTimeline} /></CardContent></Card><Card><CardHeader><SurfaceHeader title="任务属性" description="事实字段与技术口径" action={<ClipboardList size={16} />} /></CardHeader><CardContent><dl className="trusted-definition-list"><div><dt>任务类型</dt><dd>结算计算</dd></div><div><dt>数据集版本</dt><dd><code>V3.2</code></dd></div><div><dt>规则版本</dt><dd><code>Settlement_v1.0.5</code></dd></div><div><dt>数据范围</dt><dd>18 个风光场站</dd></div><div><dt>可信能力</dt><dd><Badge tone="warning">LOCAL_REAL_EXPERIMENTAL_SINGLE_HOST</Badge></dd></div><div><dt>证据锚定</dt><dd><Badge tone="warning">DEMO</Badge></dd></div></dl><Progress value={65} label="任务完成度 65%" /></CardContent></Card></div>
    <Card><CardHeader><SurfaceHeader title="当前责任" description="状态变化需要明确的下一步动作" action={<ListChecks size={16} />} /></CardHeader><CardContent><div className="trusted-next-action"><span className="trusted-next-icon"><ShieldCheck size={17} /></span><div><strong>受控计算执行中</strong><p>等待参与方 B、C 返回本地计算摘要。结果生成后由主体人工确认，不自动签署。</p></div><Button variant="secondary" onClick={() => setLogsOpen(true)}>查看日志</Button></div></CardContent></Card>
    <Dialog open={logsOpen} onOpenChange={setLogsOpen}><DialogContent className="energy-log-dialog"><DialogTitle>实时任务日志</DialogTitle><DialogDescription>演示日志流 · 不代表生产服务端实时数据</DialogDescription><div className="trusted-log-stream">{["09:35:01 Init state accepted", "09:35:03 DataAuth digest matched 7ab3…c91f", "09:35:08 Party A connector adapter ready", "09:35:12 Party B local input sealed", "09:35:18 ComputeExec batch 03/05", "09:35:21 awaiting party C digest"].map((line, index) => <div key={line}><time>09:35:{String(index * 4 + 1).padStart(2, "0")}</time><code>{line}</code></div>)}</div><Button variant="secondary" onClick={() => setLogsOpen(false)}>关闭</Button></DialogContent></Dialog>
  </PageFrame>;
}
